version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: pharma
      POSTGRES_USER: pharma
      POSTGRES_PASSWORD: pharma123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=pharma
      - DB_POSTGRESDB_USER=pharma
      - DB_POSTGRESDB_PASSWORD=pharma123
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_WEBHOOK_URL=http://localhost:5678
      - WEBHOOK_URL=http://localhost:5678
      - GENERIC_TIMEZONE=America/Bogota
      - N8N_BASIC_AUTH_ACTIVE=false
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres


volumes:
  postgres_data:
  mongo_data:
  n8n_data:
  redis_data:
