version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: pharma
      POSTGRES_USER: pharma
      POSTGRES_PASSWORD: pharma123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  n8n:
    image: n8nio/n8n
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=pharma
      - DB_POSTGRESDB_USER=pharma
      - DB_POSTGRESDB_PASSWORD=pharma123
      - N8N_HOST=localhost
      - N8N_PORT=5678
    ports:
      - "5678:5678"
    depends_on:
      - postgres
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  postgres_data:
  mongo_data:
  n8n_data:
