# src/main/resources/application-dev.yml

# Configuración **solo** para el perfil "dev"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pharma
    username: pharma
    password: pharma123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/chatdb

logging:
  level:
    ROOT: INFO

app:
  name: PharmaSync
